#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  6 19:52:07 2023

@author: behrense
"""

import matplotlib.pyplot as plt
import panda as pd

#%%
df= pd.read_csv("AntClimNow_Ocean_ACI_v1_merge.csv", index_col="Date", parse_dates=True)

#%%
plt.close('all')
fig = plt.figure(figsize=(14,8))
ax=fig.add_subplot(5,3,1)
df.Ross_gyre.plot()
plt.title('Ross Gyre')
ax=fig.add_subplot(5,3,2)
df.Weddell_gyre.plot()
plt.title('Weddell Gyre')
ax=fig.add_subplot(5,3,3)
df.ACC_transport.plot()
plt.title('ACC')
ax=fig.add_subplot(5,3,4)
df.AABW_volume.plot()
plt.title('AABW volume')
ax=fig.add_subplot(5,3,5)
df.AABW_temperature.plot()
plt.title('AABW temperature')
ax=fig.add_subplot(5,3,6)
df.AABW_salinity.plot()
plt.title('AABW salinity')
ax=fig.add_subplot(5,3,7)
df.HSSW_Ross_volume.plot()
plt.title('HSSW Ross volume')
ax=fig.add_subplot(5,3,8)
df.HSSW_Ross_temperature.plot()
plt.title('HSSW Ross temperature')
ax=fig.add_subplot(5,3,9)
df.HSSW_Ross_salinity.plot()
plt.title('HSSW Ross salinity')
ax=fig.add_subplot(5,3,10)
df.HSSW_Weddell_volume.plot()
plt.title('HSSW Weddell volume')
ax=fig.add_subplot(5,3,11)
df.HSSW_Weddell_temperature.plot()
plt.title('HSSW Weddell temperature')
ax=fig.add_subplot(5,3,12)
df.HSSW_Weddell_salinity.plot()
plt.title('HSSW Weddell salinity')
ax=fig.add_subplot(5,3,13)
df.AABW_export.plot()
plt.title('AABW overturning')
ax=fig.add_subplot(5,3,14)
df.AABW_overturning.plot()
plt.title('AABW export')

#%%
#%%
plt.close('all')
fig = plt.figure(figsize=(14,8))
ax=fig.add_subplot(5,3,1)
df.Ross_gyre.plot()
plt.xlim('2000','2023')
#%%
plt.title('Ross Gyre')
ax=fig.add_subplot(5,3,2)
df.Weddell_gyre.plot()
plt.xlim('2000','2023')
plt.title('Weddell Gyre')
ax=fig.add_subplot(5,3,3)
df.ACC_transport.plot()
plt.xlim('2000','2023')
plt.title('ACC')
ax=fig.add_subplot(5,3,4)
df.AABW_volume.plot()
plt.xlim('2000','2023')
plt.title('AABW volume')
ax=fig.add_subplot(5,3,5)
df.AABW_temperature.plot()
plt.xlim('2000','2023')
plt.title('AABW temperature')
ax=fig.add_subplot(5,3,6)
df.AABW_salinity.plot()
plt.xlim('2000','2023')
plt.title('AABW salinity')
ax=fig.add_subplot(5,3,7)
df.HSSW_Ross_volume.plot()
plt.xlim('2000','2023')
plt.title('HSSW Ross volume')
ax=fig.add_subplot(5,3,8)
df.HSSW_Ross_temperature.plot()
plt.xlim('2000','2023')
plt.title('HSSW Ross temperature')
ax=fig.add_subplot(5,3,9)
df.HSSW_Ross_salinity.plot()
plt.xlim('2000','2023')
plt.title('HSSW Ross salinity')
ax=fig.add_subplot(5,3,10)
df.HSSW_Weddell_volume.plot()
plt.xlim('2000','2023')
plt.title('HSSW Weddell volume')
ax=fig.add_subplot(5,3,11)
df.HSSW_Weddell_temperature.plot()
plt.xlim('2000','2023')
plt.title('HSSW Weddell temperature')
ax=fig.add_subplot(5,3,12)
df.HSSW_Weddell_salinity.plot()
plt.xlim('2000','2023')
plt.title('HSSW Weddell salinity')
ax=fig.add_subplot(5,3,13)
df.AABW_export.plot()
plt.xlim('2000','2023')
plt.title('AABW overturning')
ax=fig.add_subplot(5,3,14)
df.AABW_overturning.plot()
plt.xlim('2000','2023')
plt.title('AABW export')
